toggles:
  in_beta: true

search:
  uri: 'http://localhost:9200'

authentication:
  providers:
    linkedin:
      args:
        scope: ''
          #- r_emailaddress
          #- r_network
        fields: ''
          #- id
          #- email-address
          #- first-name
          #- last-name
    facebook:
      args:
        scope: ''
          #- create_event
          #- rsvp_event
          #- publish_actions
          #- publish_stream
          #- user_birthday
          #- user_events
          #- user_checkins
          #- user_location
          #- friends_location
          #- friends_checkins
          #- friends_events
    gplus:
      args:
        scope:
          - plus.me
          - plus.login
          - userinfo.profile
          - userinfo.email
