toggles:
  in_beta: true

search:
  uri: 'http://localhost:9200'

authentication:
  providers:
    linkedin:
      args:
        scope:
          - r_emailaddress
          - r_network
        fields:
          - id
          - email-address
          - first-name
          - last-name
    facebook:
      args:
        image: large
        info_fields:
          - name
          - verified
          - birthday
          - email
          - picture
        scope:
          - user_birthday
    gplus:
      args:
        scope:
          - plus.me
          - plus.login
          - userinfo.profile
          - userinfo.email
