toggles:
  in_beta: true

search:
  uri: 'http://localhost:9200'

authentication:
  providers:
    linkedin:
      scope:
        - r_emailaddress
        - r_network
      fields:
        - id
        - email-address
        - first-name
        - last-name
    facebook:
      image: 'large'
      info_fields:
        - name
        - verified
        - birthday
        - email
        - picture
      scope:
        - email
        - user_birthday
        - manage_pages
    #gplus:
      #scope:
        #- plus.me
        #- plus.login
        #- userinfo.profile
        #- userinfo.email
