toggles:
  in_beta: true
  features:
    - beta
    - auth:facebook
    - auth:linkedin

search:
  uri: <%= ENV['SEARCHBOX_URL'] %>

authentication:
  providers:
    facebook:
      id: <%= ENV['PORTCULLIS_AUTH_FACEBOOK_ID'] %>
      secret: <%= ENV['PORTCULLIS_AUTH_FACEBOOK_SECRET'] %>
    gplus:
      id: <%= ENV['PORTCULLIS_AUTH_GPLUS_ID'] %>
      secret: <%= ENV['PORTCULLIS_AUTH_GPLUS_SECRET'] %>
    linkedin:
      id: <%= ENV['PORTCULLIS_AUTH_LINKEDIN_ID'] %>
      secret: <%= ENV['PORTCULLIS_AUTH_LINKEDIN_SECRET'] %>
