toggles:
  in_beta: true
  features:
    - beta
    - auth:facebook
    - auth:gplus

authentication:
  providers:
    facebook:
      id: <%= ENV['MELODY_AUTH_FACEBOOK_ID'] %>
      secret: <%= ENV['MELODY_AUTH_FACEBOOK_SECRET'] %>
    gplus:
      id: <%= ENV['MELODY_AUTH_GPLUS_ID'] %>
      secret: <%= ENV['MELODY_AUTH_GPLUS_SECRET'] %>
